server:
  port: 8081
spring:
  application:
    name: shorturl
  datasource:
    url: jdbc:mysql://cy96151.cn:3306/short_url?characterEncoding=utf8&useSSL=false
    username: root
    password: cymysqld
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    host: cy96151.cn
    port: 6379
    password: cyredispwd
logging:
  level:
    com.cy.shorturl.mapper: debug
mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.cy.shorturl.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0